#!/bin/bash -l 
set -ex

#curl -fsSL https://starship.rs/install.sh -o install_starship.sh
#chmod +x install_starship.sh
#./install_starship.sh --yes
#echo "starship init fish | source" >> ~/.config/fish/config.fish

# echo "/usr/local/bin/fish" >> /etc/shells
# chsh -s /usr/local/bin/fish
cp terminal_workspace.json $(jupyter --config)/lab/workspaces/
