#!/bin/bash -l 
set -ex

#curl -fsSL https://starship.rs/install.sh -o install_starship.sh
#chmod +x install_starship.sh
#./install_starship.sh --yes
#echo "starship init fish | source" >> ~/.config/fish/config.fish

# echo "/usr/local/bin/fish" >> /etc/shells
# chsh -s /usr/local/bin/fish
ls -aR ~/ 
# ls -aR $(jupyter --config)
mkdir -p $(jupyter --config)/lab/workspaces/
cp ~/binder/terminal_workspace.json $(jupyter --config)/lab/workspaces/default-37a8.jupyterlab-workspace
cp ~/binder/terminal_workspace.json $(jupyter --config)/lab/workspaces/terminal-4e68.jupyterlab-workspace
